# Generated by Django 4.2.5 on 2023-09-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
